# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('short', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
